// structured-json/dataset/*.json から searchable フィールドの
// ユニーク値を収集し、src/data/facet-suggestions.ts へ出力する

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

interface SearchableFields {
  assayType?: string[]
  tissues?: string[]
  diseases?: { label: string; icd10: string | null }[]
  cellLine?: string[]
  population?: string[]
  libraryKits?: string[]
  platforms?: { vendor: string | null; model: string | null }[]
  referenceGenome?: string[]
  fileTypes?: string[]
  processedDataTypes?: string[]
  targets?: string | null
}

interface Dataset {
  experiments?: { searchable?: SearchableFields }[]
}

const structuredJsonDir = process.argv[2]
if (!structuredJsonDir) {
  // eslint-disable-next-line no-console
  console.error("Usage: tsx scripts/generate-facet-suggestions.ts <structured-json-dir>")
  process.exit(1)
}

const datasetDir = join(structuredJsonDir, "dataset")
const files = readdirSync(datasetDir).filter((f) => f.endsWith(".json"))

const sets: Record<string, Set<string>> = {
  assayType: new Set(),
  tissues: new Set(),
  diseaseLabel: new Set(),
  cellLine: new Set(),
  population: new Set(),
  libraryKits: new Set(),
  platformVendor: new Set(),
  platformModel: new Set(),
  referenceGenome: new Set(),
  fileTypes: new Set(),
  processedDataTypes: new Set(),
  targets: new Set(),
}

for (const file of files) {
  const raw = readFileSync(join(datasetDir, file), "utf-8")
  const data: Dataset = JSON.parse(raw)

  for (const exp of data.experiments ?? []) {
    const s = exp.searchable
    if (!s) continue

    for (const v of s.assayType ?? []) sets.assayType.add(v)
    for (const v of s.tissues ?? []) sets.tissues.add(v)
    for (const d of s.diseases ?? []) {
      if (d.label) sets.diseaseLabel.add(d.label)
    }
    for (const v of s.cellLine ?? []) sets.cellLine.add(v)
    for (const v of s.population ?? []) sets.population.add(v)
    for (const v of s.libraryKits ?? []) sets.libraryKits.add(v)
    for (const p of s.platforms ?? []) {
      if (p.vendor) sets.platformVendor.add(p.vendor)
      if (p.model) sets.platformModel.add(p.model)
    }
    for (const v of s.referenceGenome ?? []) sets.referenceGenome.add(v)
    for (const v of s.fileTypes ?? []) sets.fileTypes.add(v)
    for (const v of s.processedDataTypes ?? []) sets.processedDataTypes.add(v)
    if (s.targets) sets.targets.add(s.targets)
  }
}

const result: Record<string, string[]> = {}
for (const [key, set] of Object.entries(sets)) {
  result[key] = [...set].sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }))
}

// JSON.stringify の出力に trailing comma を追加 (ESLint @stylistic/comma-dangle 対応)
const jsonWithTrailingCommas = JSON.stringify(result, null, 2)
  .replace(/([^,[\]{])\n(\s*[\]}])/g, "$1,\n$2")
  .replace(/(\])\n(\s*\})/g, "$1,\n$2")

const outputPath = join(import.meta.dirname, "..", "src", "data", "facet-suggestions.ts")
const content = [
  "// Auto-generated by scripts/generate-facet-suggestions.ts",
  "",
  `export const facetSuggestions = ${jsonWithTrailingCommas}`,
  "",
].join("\n")
writeFileSync(outputPath, content)

// eslint-disable-next-line no-console
console.log("Generated facet-suggestions.ts:")
for (const [key, values] of Object.entries(result)) {
  // eslint-disable-next-line no-console
  console.log(`  ${key}: ${values.length} values`)
}
